### ISSUE TITLE
Nothing change when install using git-bash on windows

### ISSUE THREAD

**Issue by eromoe** [kepbod/ivim#41]
![6zmalt 1au0j 3ds5 ipea](https://cloud.githubusercontent.com/assets/3938751/21711069/a47820f2-d427-11e6-927c-c1be356f390d.png)

I look into `setup.sh` and find this line:
```
ln -s $HOME/.ivim/vimrc $HOME/.vimrc
```

`ln -s` not exist on windows, how about add a check like:

```
if has("win32")
   cp $HOME/.ivim/vimrc $HOME/.vimrc
endif
```
In my windows 7 , using git-bash running `cp $HOME/.ivim/vimrc $HOME/.vimrc`, and run `sh ~/.ivim/setup.sh` works fine.

**Comment by kepbod** [comment]
I tried to make ivim compatible with windows before, but found too many stuffs required to be concerned, so I give up to support windows. In addition, I am not sure shell script could also be run on windows, because the `setup.sh` is a shell script. If you have any methods to make ivim support windows better, welcome to create RPs. Thanks a lot.
